modified: '2025-08-20T03:33:45'
published: '2017-02-14T14:12:40'
slug: python-raspberry-pi-talk-fosdem
tags:
- fosdem
- gpio
- gpiozero
- python
- raspberry-pi
- raspberry-pi-foundation
title: Python and Raspberry Pi talk at FOSDEM
