modified: '2015-01-03T13:57:18'
published: '2015-01-03T01:40:49'
slug: review-of-the-year-2014
tags:
- conference
- open-source
- python
- raspberry-pi
- raspberry-pi-foundation
- review
- talks
- year-review
- career
title: Review of the Year 2014
