modified: '2026-08-16T00:40:45+01:00'
published: '2017-04-01T00:00:00'
tags:
- code
- python
- gpiozero
- raspberry-pi
- dave-jones
title: Programming Logic Gates with GPIO Zero Source/Values
og_image: images/magpi55.webp
