modified: '2026-05-07T01:34:51+01:00'
published: '2010-01-15T23:09:48'
tags:
- climb
- helvellyn
- mountain
- adventure
- lake-district
title: Midnight Ice Climb Up Helvellyn
og_image: images/DSCF0121.webp
