modified: '2026-04-30T23:01:01+01:00'
published: '2009-04-14T19:00:00'
tags:
- web-development
- blogging
- internet-explorer
- meta
title: Version 3 and Problems with IE
og_image: images/W3C_and_Internet_Explorer_box_models.webp
