modified: '2025-08-23T14:02:15+01:00'
published: '2009-04-14T19:00:00'
slug: version-3-and-problems-with-ie
tags:
- web-development
- blogging
- internet-explorer
title: Version 3 and Problems with IE
