modified: '2014-06-15T16:23:00'
published: '2014-01-05T23:55:12'
tags:
- kayaking
- manchester-raspberry-jam
- open-source
- piweekly
- raspberry-jam
- raspberry-pi
- raspberry-pi-foundation
- ubuntu
- web-development
- year-review
- madlab
- career
- talks
- github
title: 2013 in Review
og_image: images/10902018066_8456108310_b.webp
