modified: '2014-06-15T16:23:00'
published: '2014-01-05T23:55:12'
slug: 2013-in-review
tags:
- kayaking
- manchester-raspberry-jam
- open-source
- piweekly
- raspberry-jam
- raspberry-pi
- raspberry-pi-foundation
- ubuntu
- web-development
- year-review
- madlab
- career
title: 2013 in Review
