published: '2026-04-11T22:54:39+01:00'
modified: '2026-05-01T01:19:45+01:00'
tags:
- python
- blogging
- claude
- ai
- web-development
- meta
- github
- open-source
- dave-jones
- beemo
title: Beemo Analytics
og_image: images/beemo.webp
