modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-07T12:00:00'
tags:
- ruby
- open-data
- data-visualisation
- university
- datavis-project
- sheffield
- maps
title: Sheffield Motorway Matrix Displays Mapped
og_image: motorway-sign.webp