modified: '2019-04-16T13:08:56'
published: '2019-04-16T10:00:45'
tags:
- debian
- linux
- raspberry-pi
- raspbian
- ubuntu
- dave-jones
title: ranger
og_image: images/2019-04-14-233911_1440x900_scrot.webp
