modified: '2025-08-20T15:09:46'
published: '2018-03-15T12:00:00'
slug: speedy-python-package-installation-for-raspberry-pi
tags:
- raspberry-pi
- python
- piwheels
- pip
- pypi
title: Speedy Python package installation for Raspberry Pi