modified: '2026-05-07T01:58:48+01:00'
published: '2018-10-16T12:00:00'
tags:
- raspberry-pi
- python
- piwheels
- pip
- pypi
title: Speedy Python package installation for Raspberry Pi
og_image: images/piwheels-stack.webp
