modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-02T12:00:00'
tags:
- world-wide-web
- internet
- tim-berners-lee
- history
- university
- datavis-project
title: History of the Web
og_image: images/web-visualisation.webp
