modified: '2026-04-30T16:50:56+01:00'
published: '2012-04-19T17:35:41'
tags:
- bbc-news
- football
- hack
- hacking
- leak
- web-server
title: Norwich City FC Angry at Fan For Leaking New Kit
og_image: images/chris-brown-norwich-fan.webp
