modified: '2014-06-15T16:23:02'
published: '2012-04-19T17:35:41'
slug: norwich-city-angry-at-fan
tags:
- bbc-news
- football-shirt
- hack
- hacking
- leak
- web-server
title: Norwich City FC Angry at Fan For Leaking New Kit
