modified: '2014-06-15T16:23:00'
published: '2013-09-16T02:20:47'
tags:
- berlin
- germany
- raspberry-jam
- raspberry-pi
- travels
- talks
title: Berlin 2013
og_image: images/IMG_20130924_130643.resized.webp
