modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-12T12:00:00'
tags:
- matlab
- maths
- lorenz-attractor
- university
- datavis-project
title: 3D Plot & Time Series
og_image: images/lorenz-3d-plot.webp
