modified: '2025-08-20T20:52:36+01:00'
published: '2012-02-05T21:47:19'
slug: ternary-operator-shorthand-code
tags:
- boolean
- php
- python
- shorthand
- ternary-operator
title: Ternary Operator and Other Shorthand Code
