modified: '2014-06-15T16:23:01'
published: '2012-11-24T21:41:28'
slug: hack-manchester
tags:
- daylight-saving
- hack
- hack-manchester
- imdb
- mongodb
- mosi
- php
- python
- ruby
title: Hack Manchester
