modified: '2014-06-15T16:23:00'
published: '2013-04-20T20:58:13'
slug: free-software-culture-talk-bracamp
tags:
- barcamp
- madlab
- manchester-girl-geeks
- open-source
- talk
- unconference
title: Free Software Culture Talk at Manchester Bracamp
