modified: '2016-12-16T21:20:32'
published: '2016-12-16T20:34:29'
slug: all-things-open-raspberry-pi-everyone
tags:
- all-things-open
- open-source
- raspberry-pi
- raspberry-pi-foundation
- red-hat
- usa
title: All Things Open 2016 — Raspberry Pi for everyone!
