modified: '2025-08-23T12:00:23+01:00'
published: '2010-02-23T12:00:00'
slug: itv-fixers-and-absolute-radio
tags:
- itv
- absolute-radio
- dave-gorman
- parkour
- manchester
title: ITV Fixers and Absolute Radio
