modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-04T12:00:00'
tags:
- maths
- matlab
- big-numbers
- university
- datavis-project
title: What Does 1,000,000 Look Like?
og_image: images/million-cube.webp
