modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-13T12:00:00'
tags:
- matlab
- maths
- pi
- university
- datavis-project
title: "Visualising the Convergence of Pi, Calculated by the Leibniz Method"
og_image: images/pi-approximation-plot.webp
