modified: '2015-04-14T21:16:18'
published: '2014-06-26T17:17:29'
slug: linux-voice-interview
tags:
- linux
- linux-voice
- raspberry-jam
- raspberry-pi
- raspberry-pi-foundation
title: Linux Voice Interview with Raspberry Pi Education Team
