modified: '2025-08-20T14:03:45+01:00'
published: '2017-02-06T12:00:00'
slug: try-raspberry-pi-pixel-os-on-your-pc
tags:
- gpio
- gpiozero
- python
- raspberry-pi
- linux
title: Try Raspberry Pi's PIXEL OS on your PC
