published: '2025-08-23T15:50:56+01:00'
slug: another-website-revamp
tags:
- python
- blogging
- web-development
- meta
- bbc
- bbc-news
- media-city
- manchester
- github
- open-source
- pydantic
title: Another website revamp
