published: '2025-08-23T23:54:17+01:00'
modified: '2025-08-26T18:54:12+00:00'
slug: another-website-revamp
tags:
- python
- blogging
- web-development
- meta
- bbc
- bbc-news
- media-city
- manchester
- github
- open-source
- pydantic
title: Another website revamp
