published: '2025-08-23T23:54:17+01:00'
modified: '2026-05-01T01:17:14+01:00'
tags:
- python
- blogging
- web-development
- meta
- bbc
- bbc-news
- media-city
- manchester
- github
- open-source
- pydantic
- beemo
title: Another website revamp
og_image: images/media-city.webp