modified: '2014-06-15T16:23:03'
published: '2008-11-29T22:04:06'
slug: the-duke-of-edinburghs-gold-award
tags:
- duke-of-edinburghs-award
- london
- prince-philip
- scouts
title: The Duke of Edinburgh's Gold Award
