modified: '2026-04-30T17:00:12+01:00'
published: '2012-04-15T22:07:33'
tags:
- conference
- edinburgh
- stuck-in-a-lift
- whisky
- whisky-web
- scotland
- web-development
- php
title: Whisky Web
og_image: images/2012-04-13 17.49.35.webp
