modified: '2014-06-15T16:23:01'
published: '2012-10-02T21:30:48'
slug: barcamp-blackpool-2012
tags:
- barcamp
- blackpool
- freaky-clown
- twitter
- unconference
- werewolf
title: Barcamp Blackpool 2012
