modified: '2025-08-20T21:54:04+01:00'
published: '2013-01-28T00:39:57'
slug: comprehension-in-python
tags:
- comprehension
- functional-programming
- generators
- python
title: Comprehension in Python
