modified: '2017-07-31T00:49:21'
published: '2017-07-27T16:46:50'
tags:
- gpio
- gpiozero
- python
- raspberry-pi
- dave-jones
title: What's new in GPIO Zero v1.4?
og_image: images/blue_dot_feature_small.webp
