published: '2026-04-29T19:27:19+01:00'
tags:
- python
- claude
- ai
- web-development
- github
- open-source
- football
title: Getting Claude to extract data from a 1997 football manager game
og_image: images/fsm-website.webp