modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-11T12:00:00'
tags:
- maths
- chemistry
- chaos
- university
- datavis-project
title: Limit Cycle
og_image: images/belousov-zhabotinsky-phase-portrait.webp
