modified: '2014-06-15T16:23:02'
published: '2012-02-06T00:29:21'
slug: xp-manchester-xl-feb12
tags:
- agile
- kata
- manchester
- tdd
- xp-manchester
- madlab
title: XP Manchester XL — Release Early, Release Often
