modified: '2026-05-02T00:20:08+01:00'
published: '2007-06-03T15:39:52'
tags:
- france
- lisses
- parkour
- social-media
- facebook
- myspace
- meta
title: Lisses, Facebook & blog neglect
og_image: images/3_Logo-Facebook-2005-1024x446.webp
