modified: '2014-06-15T16:23:02'
published: '2011-12-01T12:25:08'
slug: ima-talk-maths-theres-an-app-for-that
tags:
- bret-victor
- ima
- maths
- mmu
- wolfram-alpha
title: "IMA Talk: Maths — There's an App For That"
