modified: '2014-06-15T16:23:04'
published: '2007-08-03T22:50:39'
slug: trace-gathering-2007
tags:
- parkour
- sheffield
- peak-district
- trace-gathering
- bbc
- bbc-inside-out
title: Trace Gathering 2007
