modified: '2026-04-30T23:24:39+01:00'
published: '2007-08-03T22:50:39'
tags:
- parkour
- sheffield
- peak-district
- trace-gathering
- bbc
- bbc-inside-out
title: Trace Gathering 2007
og_image: images/trace4.webp
