modified: '2017-08-04T00:53:18'
published: '2017-08-04T00:53:18'
slug: prototyping-raspberry-pi-robot-idea-two-emulators
tags:
- gpio
- gpiozero
- raspberry-pi
- sense-hat
- dave-jones
title: Prototyping a Raspberry Pi robot idea with two emulators
