modified: '2016-12-16T21:20:57'
published: '2016-11-16T20:34:51'
slug: pycon-russia-keynote-physical-computing-with-python-and-raspberry-pi
tags:
- gpiozero
- pycon
- python
- raspberry-pi
- raspberry-pi-foundation
- russia
title: PyCon Russia keynote — Physical computing with Python and Raspberry Pi
