modified: '2026-05-07T01:36:33+01:00'
published: '2012-09-09T23:21:28'
tags:
- linux
- madlab
- manchester
- python
- raspberry-jam
- raspberry-pi
title: Manchester Raspberry Jam Continued
og_image: images/2012-08-11_10.50.26.webp
