modified: '2014-06-15T16:23:01'
published: '2012-09-09T23:21:28'
slug: manchester-raspberry-jam-continued
tags:
- linux
- madlab
- manchester
- python
- raspberry-jam
- raspberry-pi
title: Manchester Raspberry Jam Continued
