published: '2026-06-27T01:53:01+01:00'
modified: '2026-06-28T23:19:11+01:00'
tags:
- python
- claude
- ai
- web-development
- github
- open-source
- family-tree
- genealogy
- gramps
- greatgramps
title: "greatgramps: a static site generator for Gramps family trees"
og_image: images/greatgramps.webp
