modified: '2015-01-03T02:21:34'
published: '2014-11-03T01:41:04'
slug: all-the-python-conferences
tags:
- berlin
- conference
- dublin
- germany
- ireland
- pycon
- python
- python-conference
- raspberry-pi
- raspberry-pi-foundation
- san-sebastian
- spain
- speaking
- travels
title: All the Python Conferences
