modified: '2026-05-07T01:37:25+01:00'
published: '2014-11-03T01:41:04'
tags:
- berlin
- conference
- dublin
- germany
- ireland
- pycon
- python
- python-conference
- raspberry-pi
- raspberry-pi-foundation
- san-sebastian
- spain
- speaking
- travels
- talks
title: All the Python Conferences
og_image: images/ep2014-badge.webp
