modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-06T12:00:00'
tags:
- php
- matlab
- rubiks-cube
- data-visualisation
- university
- datavis-project
title: "Rubik's Cube Data from Android App"
og_image: images/solve-times-with-average.webp
