modified: '2014-06-15T16:23:01'
published: '2012-07-31T21:19:06'
slug: preposition
tags:
- beavis-butthead
- english-language
- grammar
- preposition
- whacking
title: 'My Hobby: Not Ending Sentences with a Preposition'
