modified: '2021-09-28T13:19:46'
published: '2021-04-12T04:09:53'
slug: the-surreal-experience-of-my-first-developer-job
tags:
- web-development
- media-city
- manchester
- career
title: The surreal experience of my first developer job
