modified: '2016-10-28T15:13:56'
published: '2016-08-18T16:37:46'
tags:
- gpio
- gpiozero
- python
- raspberry-pi
- raspberry-pi-foundation
title: Simple Electronics with GPIO Zero book
og_image: images/GPIOZeroSpread-300x213.webp
