modified: '2017-03-19T20:06:14'
published: '2017-03-19T01:28:48'
slug: google-onhub-the-best-router-ive-ever-owned
tags:
- google-onhub
- google-wifi
- google
- router
- tortoise
- dave-jones
title: "Google OnHub: the best router I've ever owned"
