modified: '2020-01-30T17:43:24'
published: '2020-01-26T17:11:30'
slug: goodbye-raspberry-pi-hello-bbc
tags:
- bbc
- bbc-news
- bbc-news-labs
- raspberry-pi
- raspberry-pi-foundation
- career
title: Goodbye Raspberry Pi, Hello BBC
