modified: '2020-01-30T17:43:24'
published: '2020-01-26T17:11:30'
tags:
- bbc
- bbc-news
- bbc-news-labs
- raspberry-pi
- raspberry-pi-foundation
- career
title: Goodbye Raspberry Pi, Hello BBC
og_image: images/bbc-w1a.webp
