modified: '2016-04-07T16:00:50'
published: '2016-01-11T23:21:45'
slug: gpio-zero-developing-a-new-friendly-python-api-for-physical-computing
tags:
- github
- gpio
- gpiozero
- open-source
- physical-computing
- python
- raspberry-pi
- raspberry-pi-foundation
- dave-jones
title: 'GPIO Zero: Developing a new friendly Python API for Physical Computing'
