modified: '2025-08-23T13:45:00+01:00'
published: '2009-04-27T12:00:00'
slug: lots-of-training-and-a-session-with-the-bbc
tags:
- parkour
- bbc
- manchester
title: Lots of Training and a Session with the BBC
