modified: '2014-06-15T16:23:00'
published: '2013-03-24T13:47:00'
slug: raspberry-jamboree-2013
tags:
- conference
- manchester
- raspberry-jam
- raspberry-jamboree
- raspberry-pi
title: Raspberry Jamboree 2013
