modified: '2025-08-22T17:51:22+01:00'
published: '2012-10-02T13:07:56'
slug: hero-kayakers
tags:
- hero
- irwell
- kayaking
- manchester-evening-news
- rescue
- river
- bbc-news
title: Hero Kayakers Rescue Whitewater Dinghy Man
