modified: '2026-05-07T01:36:19+01:00'
published: '2012-10-02T13:07:56'
tags:
- hero
- irwell
- kayaking
- manchester-evening-news
- rescue
- river
- bbc-news
title: Hero Kayakers Rescue Whitewater Dinghy Man
og_image: images/hero.webp
