modified: '2020-05-29T21:31:29'
published: '2018-10-04T00:11:23'
slug: europython-pycon-uk-and-a-john-pinner-award
tags:
- europython
- pycon
- python
title: EuroPython, PyCon UK and a John Pinner Award
