modified: '2026-05-06T15:46:25+01:00'
published: '2006-07-16T23:48:40'
tags:
- manchester
- parkour
- peak-district
- sheffield
- trace-gathering
title: Northern Parkour Gathering 2006
og_image: images/P1030171.webp
