modified: '2014-06-15T16:23:04'
published: '2006-07-16T23:48:40'
slug: northern-parkour-gathering-2006
tags:
- manchester
- parkour
- peak-district
- sheffield
- trace-gathering
title: Northern Parkour Gathering 2006
