modified: '2026-06-09T00:42:04+01:00'
published: '2006-07-16T23:48:40'
tags:
- manchester
- parkour
- peak-district
- sheffield
- trace-gathering
title: Northern Parkour Gathering 2006
og_image: images/P1030171.webp
