modified: '2026-05-07T01:34:04+01:00'
published: '2009-07-30T19:48:47'
tags:
- austria
- france
- kayaking
- travels
- switzerland
- dave-gorman
title: French & Austrian Alps 2009
og_image: images/DSC01178.webp
