modified: '2026-05-07T01:36:26+01:00'
published: '2012-07-18T23:02:02'
tags:
- linux
- madlab
- manchester
- python
- raspberry-jam
- raspberry-pi
- talks
title: Manchester Raspberry Jam
og_image: images/2012-07-14-10.47.13.webp
