modified: '2014-06-15T16:23:01'
published: '2012-07-18T23:02:02'
slug: manchester-raspberry-jam
tags:
- linux
- madlab
- manchester
- python
- raspberry-jam
- raspberry-pi
title: Manchester Raspberry Jam
