modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-14T12:00:00'
tags:
- matlab
- colour
- data-visualisation
- university
- datavis-project
title: 16,777,216 Colours
og_image: images/all-colours-sorted.webp
