modified: '2026-08-19T01:08:19+01:00'
published: '2011-08-10T12:00:00'
tags:
- matlab
- maths
- chaos
- pendulum
- university
- datavis-project
title: Double Pendulum
og_image: images/double-pendulum-diagram.webp
