modified: '2014-06-15T16:23:00'
published: '2013-11-09T01:38:28'
tags:
- piweekly
- raspberry-pi
- raspberry-pi-foundation
- career
title: Pi Weekly — MVP, Evolution and My Dream Job
og_image: images/piweekly-archive.webp
